# SPDX-FileCopyrightText: 2024 Rajul Jha <rajuljha49@gmail.com>
#
# SPDX-License-Identifier: GPL-2.0-only

name: "FOSSology Scan + SPDX 3.0"
description: "Run license and copyright scans with SPDX 3.0 JSON-LD report generation"
author: "Rajul Jha"
branding:
  icon: "search"
  color: "orange"
inputs:
  # Customizable input variables
  scan_mode:
    description: "Run the scan in one of the following modes: repo, differential, scan-only-deps, scan-dir"
    required: false
    default: "diff"
  scanners:
    description: "One of the scanner to invoke: nomos, copyright, keyword, ojo"
    required: false
    default: "nomos ojo copyright keyword"
  report_format:
    description: "Report format to generate reports in: TEXT, SPDX_JSON, SPDX_YAML, SPDX_RDF, SPDX_TAG_VALUE, SPDX3_JSON"
    required: false
    default: "TEXT"
  keyword_conf_file_path:
    description: "Path to custom keyword.conf file"
    required: false
    default: ""
  allowlist_file_path:
    description: "Path to allowlist.json file"
    required: false
    default: ""
  from_tag:
    description: "If in differential mode, can provide a starting tag to scan from. Ex. v1"
    required: false
    default: ""
  to_tag:
    description: "If in differential mode, can provide an ending tag to scan to. Ex. v2"
    required: false
    default: ""
  sbom_path:
    description: "If in scan-only-deps mode, path of of the SBOM file to scan."
    required: false
    default: "sbom.json"
  scan_dir:
    description: "If in scan-dir mode, path of the directory to scan."
    required: false
    default: ""
  # Internal Variables. Not meant to be passed by the user. These are set up by the action itself.
  github_api_url:
    description: "Base URL of Github API"
    required: false
    default: ${{ github.api_url }}
  github_repository:
    description: "Repository name"
    required: false
    default: ${{ github.repository }}
  github_token:
    description: "Github Token"
    required: false
    default: ${{ github.token }}
  github_pull_request:
    description: "Github PR"
    required: false
    default: ${{ github.event.number }}
  github_repo_url:
    description: "Github Repo URL"
    required: false
    default: ${{ github.repositoryUrl }}
  github_repo_owner:
    description: "Github Repo Owner"
    required: false
    default: ${{ github.repository_owner }}

runs:
  using: 'docker'
  image: 'docker://ghcr.io/shatakshisgtiwari-jpg/fossology-spdx3:latest'
  entrypoint: '/opt/entrypoint.sh'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_PULL_REQUEST: ${{ inputs.github_pull_request }}
    GITHUB_REPOSITORY: ${{ inputs.github_repository }}
    GITHUB_API: ${{ inputs.github_api_url }}
    GITHUB_REPO_URL: ${{ inputs.github_repo_url }}
    GITHUB_REPOSITORY_OWNER: ${{ inputs.github_repo_owner }}
  args: []
